import { buildInfo } from "../../utils/types.ts";
import {
  ballInCageGallery,
  bedHeadboardGallery,
  birdHouseGallery,
  chaosCuttingBoardGallery,
  cornHoleLawnGameGallery,
  deckRebuildGallery,
  desktopChristmasTreesGallery,
  dogHouseGallery,
  floatingBedFrameGallery,
  floatingWineHoldersGallery,
  giantJengaGallery,
  hardwoodEarringsGallery,
  heartShapedVineMountGallery,
  patioChairsGallery,
  patioTablesGallery,
  petFoodDispenserGallery,
  plantingStationGallery,
  soapSaversGallery,
  squirrelPicnicTableGallery,
  tensegrityModelGallery,
  vortexWaterFountainGallery,
  workBenchGallery,
} from "./gallery-data.ts";

import {
  ballInCageDescription,
  bedHeadboardDescription,
  birdHouseDescription,
  chaosCuttingBoardDescription,
  cornHoleLawnGameDescription,
  deckRebuildDescription,
  desktopChristmasTreesDescription,
  dogHouseDescription,
  floatingBedFrameDescription,
  floatingWineHoldersDescription,
  giantJengaDescription,
  hardwoodEarringsDescription,
  heartShapedVineMountDescription,
  patioChairsDescription,
  patioTablesDescription,
  petFoodDispenserDescription,
  plantingStationDescription,
  soapSaversDescription,
  squirrelPicnicTableDescription,
  tensegrityModelDescription,
  vortexWaterFountainDescription,
  workBenchDescription,
} from "./description-data.ts";

export const buildData: buildInfo[] = [
  {
    id: "FXfQa9346Zw",
    name: "Ball In Cage",
    description: ballInCageDescription,
    imageGallery: ballInCageGallery,
  },
  {
    id: "7UGHJCWxci0",
    name: "Bed Headboard",
    description: bedHeadboardDescription,
    imageGallery: bedHeadboardGallery,
  },
  {
    id: "TOMa-dLfkWg",
    name: "Bird House",
    description: birdHouseDescription,
    imageGallery: birdHouseGallery,
  },
  {
    id: "kVV8znTCH1Y",
    name: "Chaos Cutting Board",
    description: chaosCuttingBoardDescription,
    imageGallery: chaosCuttingBoardGallery,
  },
  {
    id: "rZk3z2MdaAc",
    name: "Corn Hole Lawn Game",
    description: cornHoleLawnGameDescription,
    imageGallery: cornHoleLawnGameGallery,
  },
  {
    id: "YpOj7Mq0y_g",
    name: "Deck Rebuild",
    description: deckRebuildDescription,
    imageGallery: deckRebuildGallery,
  },
  {
    id: "m_yPYMZOZ2U",
    name: "Desktop Christmas Trees",
    description: desktopChristmasTreesDescription,
    imageGallery: desktopChristmasTreesGallery,
  },
  {
    id: "ssmfQXo2Aqc",
    name: "Dog House",
    description: dogHouseDescription,
    imageGallery: dogHouseGallery,
  },
  {
    id: "M5258viSFSM",
    name: "Floating Bedframe",
    description: floatingBedFrameDescription,
    imageGallery: floatingBedFrameGallery,
  },
  {
    id: "ELxkCLKPEs0",
    name: "Floating Wine Holders",
    description: floatingWineHoldersDescription,
    imageGallery: floatingWineHoldersGallery,
  },
  {
    id: "tK6kZ52l3wI",
    name: "Giant Jenga",
    description: giantJengaDescription,
    imageGallery: giantJengaGallery,
  },
  {
    id: "1T9l0oV8QrQ",
    name: "Hardwood Earrings",
    description: hardwoodEarringsDescription,
    imageGallery: hardwoodEarringsGallery,
  },
  {
    id: "zr7yIyB9S5E",
    name: "Heart Shaped Vine Mount",
    description: heartShapedVineMountDescription,
    imageGallery: heartShapedVineMountGallery,
  },
  {
    id: "DSj2zrO9OKg",
    name: "Patio Chairs",
    description: patioChairsDescription,
    imageGallery: patioChairsGallery,
  },
  {
    id: "QmzxZlnkxMs",
    name: "Patio Tables",
    description: patioTablesDescription,
    imageGallery: patioTablesGallery,
  },
  {
    id: "hZV0mW659pc",
    name: "Pet Food Dispenser",
    description: petFoodDispenserDescription,
    imageGallery: petFoodDispenserGallery,
  },
  {
    id: "hZV0mW659pc",
    name: "Planting Station",
    description: plantingStationDescription,
    imageGallery: plantingStationGallery,
  },
  {
    id: "RxZp-cL32rQ",
    name: "Soap Savers",
    description: soapSaversDescription,
    imageGallery: soapSaversGallery,
  },
  {
    id: "n1U-CJgrnIM",
    name: "Squirrel Picnic Tables",
    description: squirrelPicnicTableDescription,
    imageGallery: squirrelPicnicTableGallery,
  },
  {
    id: "5fstT-vTEL0",
    name: "Tensegrity Models",
    description: tensegrityModelDescription,
    imageGallery: tensegrityModelGallery,
  },
  {
    id: "_h3m9S_FHNk",
    name: "Vortex Water Fountain",
    description: vortexWaterFountainDescription,
    imageGallery: vortexWaterFountainGallery,
  },
  {
    id: "Ki3rK9v2Tx8",
    name: "Work Bench",
    description: workBenchDescription,
    imageGallery: workBenchGallery,
  },
];
